language: go

go:
  - 1.8

env:
  global:
  - SOURCE_DIR="public"

branches:
  only:
  - master

cache:
  directories:
  - "$HOME/gopath/bin/"
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
  - tar -xvzf hugo_0.18.1_Linux-64bit.tar.gz
  - cd hugo_0.18.1_linux_amd64
  - mv hugo_0.18.1_linux_amd64 hugo
  - mv hugo $HOME/gopath/bin/
  - cd ..

script:
- hugo
