language: go
go:
- 1.8
branches:
  only:
  - master
cache:
  directories:
  - $HOME/gopath/bin/
install:
- wget https://github.com/spf13/hugo/releases/download/v0.18.1/hugo_0.18.1_Linux-64bit.tar.gz
- tar -xvzf hugo_0.18.1_Linux-64bit.tar.gz
- cd hugo_0.18.1_linux_amd64
- mv hugo_0.18.1_linux_amd64 hugo
- mv hugo $HOME/gopath/bin/
- cd ..
script:
- hugo
addons:
  ssh_known_hosts: rsync.keycdn.com
before_deploy:
  - openssl aes-256-cbc -K $encrypted_9660fd890ffa_key -iv $encrypted_9660fd890ffa_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz --delete-after --quiet --chmod=u=rwX,g=rX $TRAVIS_BUILD_DIR/public/ banks@rsync.keycdn.com:zones/chloebanks/
  on:
    branch: master
