---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- path: content/pages
  label: Pages
  create: all
  default_front_matter_template: pages
- path: content/posts
  label: Posts
  create: all
  default_front_matter_template: posts
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
version: 0.18.1
